### ISSUE TITLE
Question 🙋‍♂️ 

### ISSUE THREAD

**Issue by charleslcso** [kid1194/frappe-better-attach-control#13]
Hello kid1194,

Thanks for your script. 

Before installing it may I ask, where is this better-attach UI element located?

I would like to have an upload button placed in list view, and not in any Doc form. Is this possible?

**Comment by kid1194** [comment]
@charleslcso Hey bro..

> Thanks for your script.

You are welcome buddy..

> Before installing it may I ask, where is this better-attach UI element located?

This plugin improves the Attach and Attach Image fields in form and web form..

> I would like to have an upload button placed in list view, and not in any Doc form. Is this possible?

This is not possible directly using this plugin.
But to achieve what you want, you will need a client script targeting the list view of your doctype and you will need a server script to store the attachment files..

So my question for you is, can you create server scripts or not?

Best regards..

**Comment by charleslcso** [comment]
Yes, I can create server script.

**Comment by kid1194** [comment]
@charleslcso Ok..

1. Do you want the upload button for each row?
2. Is there a doctype where you want to store the uploaded file?

**Comment by charleslcso** [comment]
I want 3 upload buttons above the first row of Contact. 

From what I read, I believe I should upload files to DocType File. I'm not sure at the moment, and need to study more. 

Basically each user should own their own files, and not readable by others. 

In Client Script, I don't think the existing methods allow me to add this upload button. I need to add it manually and then hook up events to it manually. Am I on the right path?

**Comment by kid1194** [comment]
@charleslcso You must add the buttons manually like:

```
frappe.listview_settings['Contact'] = {
    onload: function(list) {
        list.page.add_button(
            __('Upload'),
            function() {
                // On button click event
                frappe.prompt(
                    [
                        {
                            name: 'upload',
                            label: __('Upload'),
                            fieldtype: 'Attach'
                        }
                    ],
                    function(values) {
                        // Handle the upload file like: values.upload
                    },
                    __('Upload File'),
                    __('Submit')
                );
            },
            {btn_class: 'btn-success'}
        );
    }
};
```

I'm not sure if the Attach field will automatically upload the file and save it in the File doctype or not so you should give it a try..

If it does upload the file, then there is no need for the server script and the value of `values.upload` will be the uploaded file path, ex: `files/some-file.jpg`..

I hope that I was helpful..

Best regards..

**Comment by charleslcso** [comment]
Will try today. Nice n appreciated! Also will let you know the result!

**Comment by charleslcso** [comment]
Yes, it works. 

Files are uploaded, in user's own File Manager.

However, I need 2 changes:

1. location of button to be at tip of arrow
![Screen Shot 2023-05-19 at 10 42 25 PM](https://github.com/kid1194/frappe-better-attach-control/assets/520537/025557b2-2a66-451c-aac9-ba71254745dd)


2. I want to include file path to the right of the button, similar to Website settings
![Screen Shot 2023-05-19 at 10 45 43 PM](https://github.com/kid1194/frappe-better-attach-control/assets/520537/84e0e81d-c97d-47f5-9c9d-0e58f991b3fb)

I'll see if I can figure both out.

Thanks a lot!

**Comment by kid1194** [comment]
@charleslcso You can do that but indirectly, not like adding the upload buttons..

My advice is that you use the way mentioned above since it is the easiest.

But if you still want to change the list layout, you will need to override a list method and handle the buttons click event manually, something like the following..

⚠️ BTW, I don't know if the following code will work or not and I don't know if it will look good or will miss the list layout, so use at your own risk..

```
frappe.listview_settings['Contact'] = {
    onload: function(list) {
        list.get_header_html_skeleton = function(left = "", right = "") {
            return `
                <div class="level text-muted">
                    <div class="level-left">
                        <button type="button" class="first_upload_btn btn btn-success btn-sm">
                            ${__('Upload')}
                        </button>
                        <div class="first_upload_value mx-2" style="display: none"></div>
                    </div>
                    <div class="level-left">
                        <button type="button" class="second_upload_btn btn btn-success btn-sm">
                            ${__('Upload')}
                        </button>
                        <div class="second_upload_value mx-2" style="display: none"></div>
                    </div>
                </div>
                <header class="level list-row-head text-muted">
                    <div class="level-left list-header-subject">
                        ${left}
                    </div>
                    <div class="level-left checkbox-actions">
                        <div class="level list-subject">
                            <input class="level-item list-check-all" type="checkbox"
                                title="${__("Select All")}">
                            <span class="level-item list-header-meta"></span>
                        </div>
                    </div>
                    <div class="level-right">
                        ${right}
                    </div>
                </header>
            `;
        };
        // Buttons click event delegation 
        list._build_upload_prompt = function(selector) {
            frappe.prompt(
                [
                    {
                        name: 'upload',
                        label: __('Upload'),
                        fieldtype: 'Attach'
                    }
                ],
                function(values) {
                    // Handle the upload file like: values.upload
                    list.page.wrapper.find(selector)
                        .first().html(values.upload).removeAttr('style');
                },
                __('Upload File'),
                __('Submit')
            );
        };
        list.page.wrapper.on('click', '.first_upload_btn', function() {
            // On button click event
            list._build_upload_prompt('.first_upload_value');
        });
        list.page.wrapper.on('click', '.second_upload_btn', function() {
            // On button click event
            list._build_upload_prompt('.second_upload_btn');
        });
    }
};
```

Best regards..

**Comment by charleslcso** [comment]
Hello, thank you to help!

It is interesting that I can override the JS method in such a way.

After some testing, it seems that I cannot override method like this. It has no effect. I'm sure the additions are in place as I can see it in web browser Console, the line will be called, but it just won't have any effect.

No errors in web browser Debug too.

Any idea?

**Comment by kid1194** [comment]
@charleslcso It seems that the method gets called before it is overridden..

How about doing like..

```
frappe.listview_settings['Contact'] = {
    onload: function(list) {
        let head = list.page.wrapper.find('header.list-row-head');
        if (!head.length) {
            console.log('Unable to find the table head.');
            return;
        }
        head.first().before($(`
            <div class="level text-muted">
                <div class="level-left">
                    <button type="button" class="first_upload_btn btn btn-success btn-sm">
                        ${__('Upload')}
                    </button>
                    <div class="first_upload_value mx-2" style="display: none"></div>
                </div>
                <div class="level-left">
                    <button type="button" class="second_upload_btn btn btn-success btn-sm">
                        ${__('Upload')}
                    </button>
                    <div class="second_upload_value mx-2" style="display: none"></div>
                </div>
            </div>
        `));
        // Buttons click event delegation 
        list._build_upload_prompt = function(selector) {
            frappe.prompt(
                [
                    {
                        name: 'upload',
                        label: __('Upload'),
                        fieldtype: 'Attach'
                    }
                ],
                function(values) {
                    // Handle the upload file like: values.upload
                    list.page.wrapper.find(selector)
                        .first().html(values.upload).removeAttr('style');
                },
                __('Upload File'),
                __('Submit')
            );
        };
        list.page.wrapper.on('click', '.first_upload_btn', function() {
            // On button click event
            list._build_upload_prompt('.first_upload_value');
        });
        list.page.wrapper.on('click', '.second_upload_btn', function() {
            // On button click event
            list._build_upload_prompt('.second_upload_btn');
        });
    }
};
```

Best regards..

**Comment by charleslcso** [comment]
Nice, this approach works. No need to override JS. It will be good if I can override JS too! But that should be another topic.

My final design should be:
* show the full file link as shown previously
* click the button and it brings up the upload dialog, instead of bringing up the Attach dialog.

Much much appreciate your help.

![Screenshot 2023-05-22 at 12 04 05 PM](https://github.com/kid1194/frappe-better-attach-control/assets/520537/68afcc44-af8e-4013-900a-d31f0637afbc)


The button in the attached graphic has the following properties:
`<button class="btn btn-default btn-sm btn-attach" data-fieldtype="Attach" data-fieldname="favicon" placeholder="" data-doctype="Website Settings" style="display: none;">Attach</button>`

This code is for use within the Form, so some of the fields shouldn't be relevant to me. 

It is quite strange for the JS object "values"
![Screen](https://github.com/kid1194/frappe-better-attach-control/assets/520537/499d8abe-36f1-4a77-9163-0df0c3e59946)

Oh, the reason is being that we cannot use `name: 'upload'`, it has to be `fieldname: 'upload'`

I believe it should not be hard to revise the code to upload file privately.

**Comment by kid1194** [comment]
@charleslcso I'm glad that I was able to help..

And regarding the `fieldname` property, I'm sorry that I didn't realize my mistake and caused you some problems..

The good thing is that you found tge mistake and fixed it..

Best regards..
