### ISSUE TITLE
[BUG]: Missing comma in field.py

### ISSUE THREAD

**Issue by ghost** [kid1194/frappe-better-attach-control#14]
frappe/apps/frappe_better_attach_control/frappe_better_attach_control/api/field.py

a missing comma is causing the program to break on line 35

**Comment by kid1194** [comment]
@nn-dmt Thanks a lot buddy for reporting this bug..

I have fixed the missing "," and updated the plugin..
Please give it another try and let me know if you face any problem..

Best regards..
