### ISSUE TITLE
[REQ]: Option to NOT auto-save after pressing "Upload".

### ISSUE THREAD

**Issue by aakashhgoud** [kid1194/frappe-better-attach-control#19]
**Is your feature request related to a problem? Please describe.**
I have some fields which needs to filled even after uploading an attachment. 
The problem is better-attach-control has code to autosave the form right after an attachment is uploaded. 

**Describe the solution you'd like**
An option to not save the form right after uploading the attachment without affecting the core module.

**Describe alternatives you've considered**
The same autosave code exists even in the original frappe app's attach-control code.
The forum suggested to remove the line of autosave in the core module. But it's not a reliable workaround as merge conflicts can arise during version upgrades. 
I also tried removing the autosave code from better-attach-control, but for some reason even that was getting overridden and the original attach-control is getting opened or getting saved directly.

**Comment by kid1194** [comment]
@kashgod Thank you bro for using this plugin and sorry for my late response..

I have implemented this and I hope that it works without any problem..

Best regards..
