### ISSUE TITLE
[REQ]: Upload Options enable disable 

### ISSUE THREAD

**Issue by galaxlabs** [kid1194/frappe-better-attach-control#20]
** Some time not allow access to library as per user  permissions, disable/enable check for privet/public , enable/disable - library  enable/disable - link enable/disable make-all-public/make-all-privet

**Comment by kid1194** [comment]
@galaxlabs Thank you bro for your suggestion..

I have added **users** and **roles** options to help in specifying custom options for a single or group of users or roles. These custom options will modify the general options..

I hope that it works well without any problem..

Best regards..
