### ISSUE TITLE
Image Not Attaching

### ISSUE THREAD

**Issue by woakes070048** [kid1194/frappe-better-attach-control#3]
Okay so we installed the master branch and we can't get attach any document/ image to the upload button. The standard behavior is for the attached file to link to the upload button.

**Comment by kid1194** [comment]
@woakes070048 Thank you for testing the v2 Beta of this plugin..

Can you further explain the issue and provide screenshots if possible?

**Comment by kid1194** [comment]
@woakes070048 Since you haven't responded for a long time, I will consider this bug report as not related..

Best regards..
