### ISSUE TITLE
[BUG]: Attach issue.

### ISSUE THREAD

**Issue by mohsinalimat** [kid1194/frappe-better-attach-control#6]
![Screenshot 2023-01-30 at 4 40 11 PM](https://user-images.githubusercontent.com/973676/215463816-d9d8cdde-14e7-4f03-8c32-b6124ef3270d.png)
![Screenshot 2023-01-30 at 4 40 34 PM](https://user-images.githubusercontent.com/973676/215463831-e163a8a3-ac89-403f-94e3-7a41852af84c.png)

**Comment by kid1194** [comment]
@mohsinalimat Thanks a lot for reporting and fixing this bug..
